name: Fabricar APK de Gerard
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargando codigo
        uses: actions/checkout@v4

      - name: Instalando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usamos una versión de Node más actual

      - name: Instalando Cordova
        run: npm install -g cordova

      - name: Construir Proyecto Android
        run: |
          cordova platform add android
          cordova build android --debug

      - name: Entregar APK
        uses: actions/upload-artifact@v4
        with:
          name: Laboratorio_Quimico_Gerard
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
