name: Fabricar APK de Gerard
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Instalar Cordova
        run: npm install -g cordova

      - name: Construir Proyecto
        run: |
          cordova platform add android
          cordova build android --debug

      - name: Entregar APK
        uses: actions/upload-artifact@v3
        with:
          name: Laboratorio_Quimico_Gerard
          path: platforms/android/app/build/outputs/apk/debug/app-debug.apk
          
